import { Products } from "@/types/types";

export const productsData: Products[] = [
    {
        id: "1001",
        title: "Graphic Zipper Hoodie",
        price: "3,290",
        image: "/hoodies/h6.webp",
        category: "men",
        type: "hoodie",
        description: "Stay cozy and stylish this winter with our Graphic Hoodie - 5007. Made with high-quality fleece fabric, our men's hoodies provide maximum warmth and comfort. Perfect for the colder months, this hoodie is a must-have in your winter collection. Upgrade your wardrobe with this essential piece!",
    },
    {
        id: "1002",
        title: "Hoodie",
        price: "2,290",
        image: "/hoodies/h8.webp",
        category: "women",
        type: "hoodie",
        description: "Stay cozy and stylish this winter with our Graphic Hoodie - 5007. Made with high-quality fleece fabric, our men's hoodies provide maximum warmth and comfort. Perfect for the colder months, this hoodie is a must-have in your winter collection. Upgrade your wardrobe with this essential piece!",
    },
    {
        id: "1003",
        title: "Striped Graphic Hoodie",
        price: "2,790",
        image: "/hoodies/h7.webp",
        category: "men",
        type: "hoodie",
        description: "Stay cozy and stylish this winter with our Graphic Hoodie - 5007. Made with high-quality fleece fabric, our men's hoodies provide maximum warmth and comfort. Perfect for the colder months, this hoodie is a must-have in your winter collection. Upgrade your wardrobe with this essential piece!",
    },
    {
        id: "1004",
        title: "Blue Graphic Hoodie",
        price: "2,790",
        image: "/hoodies/h1.webp",
        category: "men",
        type: "hoodie",
        description: "Stay cozy and stylish this winter with our Graphic Hoodie - 5007. Made with high-quality fleece fabric, our men's hoodies provide maximum warmth and comfort. Perfect for the colder months, this hoodie is a must-have in your winter collection. Upgrade your wardrobe with this essential piece!",
    },
    {
        id: "1005",
        title: "Black Graphic Hoodie",
        price: "2,690",
        image: "/hoodies/h2.webp",
        category: "men",
        type: "hoodie",
        description: "Stay cozy and stylish this winter with our Graphic Hoodie - 5007. Made with high-quality fleece fabric, our men's hoodies provide maximum warmth and comfort. Perfect for the colder months, this hoodie is a must-have in your winter collection. Upgrade your wardrobe with this essential piece!",
    },
    {
        id: "1006",
        title: "Fone Graphic Hoodie",
        price: "2,890",
        image: "/hoodies/h3.webp",
        category: "men",
        type: "hoodie",
        description: "Stay cozy and stylish this winter with our Graphic Hoodie - 5007. Made with high-quality fleece fabric, our men's hoodies provide maximum warmth and comfort. Perfect for the colder months, this hoodie is a must-have in your winter collection. Upgrade your wardrobe with this essential piece!",
    },

    {
        id: "1007",
        title: "Gray Graphic Hoodie",
        price: "2,690",
        image: "/hoodies/h4.webp",
        category: "men",
        type: "hoodie",
        description: "Stay cozy and stylish this winter with our Graphic Hoodie - 5007. Made with high-quality fleece fabric, our men's hoodies provide maximum warmth and comfort. Perfect for the colder months, this hoodie is a must-have in your winter collection. Upgrade your wardrobe with this essential piece!",
    },
    {
        id: "1008",
        title: "Graphic Hoodie Zipper",
        price: "2,990",
        image: "/hoodies/h5.webp",
        category: "men",
        type: "hoodie",
        description: "Stay cozy and stylish this winter with our Graphic Hoodie - 5007. Made with high-quality fleece fabric, our men's hoodies provide maximum warmth and comfort. Perfect for the colder months, this hoodie is a must-have in your winter collection. Upgrade your wardrobe with this essential piece!",
    },
    {
        id: "1009",
        title: "Side Striped Trousers",
        price: "4,999",
        image: "/trousers/t1.webp",
        category: "women",
        type: "trouser",
        description: "Pick Side Striped Trousers for a casual day out and enjoy trend-led vibes.",
    },
    {
        id: "1010",
        title: "Navy Striped Trousers",
        price: "2,059",
        image: "/trousers/t2.webp",
        category: "women",
        type: "trouser",
        description: "Uplift your summer closet with our Navy Side Striped Knitted Trousers. They feature a contrast drawstring waistband for a comfortable fit and pockets. The contrasting side stripes and knitted fabric add texture for a truly unique style. These knitted trousers are a must-have for your casual looks.",
    },
    {
        id: "1011",
        title: "Trousers With Snap Buttons",
        price: "4,699",
        image: "/trousers/t3.webp",
        category: "women",
        type: "trouser",
        description: "Inject sophistication to your everyday look with our Trousers With Snap Buttons.",
    },
    {
        id: "1012",
        title: "Basic Slim Fit Trousers",
        price: "4,999",
        image: "/trousers/t4.webp",
        category: "men",
        type: "trouser",
        description: "Make your downtime more casual and preppy with these Basic Slim Fit Trousers.",
    },
    {
        id: "1013",
        title: "Striped Fit Trousers",
        price: "5,499",
        image: "/trousers/t5.webp",
        category: "men",
        type: "trouser",
        description: "Make your downtime more casual and preppy with these Basic Slim Fit Trousers.",
    },
    {
        id: "1014",
        title: "Graphic T-Shirt",
        price: "1,190",
        image: "/t-shirts/t1.webp",
        category: "men",
        type: "tee",
        description: "Make your downtime more casual and preppy with these Basic Slim Fit Trousers.",
    },
    {
        id: "1015",
        title: "Graphic T-Shirt",
        price: "1,390",
        image: "/t-shirts/t2.webp",
        category: "men",
        type: "tee",
        description: "Make your downtime more casual and preppy with these Basic Slim Fit Trousers.",
    },
    {
        id: "1016",
        title: "Essential T-Shirt",
        price: "990",
        image: "/t-shirts/t3.webp",
        category: "women",
        type: "tee",
        description: "Make your downtime more casual and preppy with these Basic Slim Fit Trousers.",
    },
    {
        id: "1017",
        title: "Essential Polo Shirt",
        price: "1990",
        image: "/polo/p1.webp",
        category: "men",
        type: "polo",
        description: "Make your downtime more casual and preppy with these Basic Slim Fit Trousers.",
    },
    {
        id: "1018",
        title: "Essential Polo Shirt",
        price: "1990",
        image: "/polo/p2.webp",
        category: "women",
        type: "polo",
        description: "Preppy with these Basic Slim Fit Trousers.",
    },
]